// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6tiYNJ1rIg6G4DPFHU6fH9RHCsKgJddE',
    appId: '1:736055369565:web:6df295e4cb378a48a0d2b4',
    messagingSenderId: '736055369565',
    projectId: 'flutter-firebase-97df9',
    authDomain: 'flutter-firebase-97df9.firebaseapp.com',
    storageBucket: 'flutter-firebase-97df9.firebasestorage.app',
    measurementId: 'G-280T7E5RXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj6x7DkxMUYpBDiMp5JkK0YEBUgUgCUHU',
    appId: '1:736055369565:android:04e5b5dca872744ea0d2b4',
    messagingSenderId: '736055369565',
    projectId: 'flutter-firebase-97df9',
    storageBucket: 'flutter-firebase-97df9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAueIYNqm3kCZ1dI0DL6PQ-ZMxCUrFwJFI',
    appId: '1:736055369565:ios:a540f728316b6435a0d2b4',
    messagingSenderId: '736055369565',
    projectId: 'flutter-firebase-97df9',
    storageBucket: 'flutter-firebase-97df9.firebasestorage.app',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAueIYNqm3kCZ1dI0DL6PQ-ZMxCUrFwJFI',
    appId: '1:736055369565:ios:a540f728316b6435a0d2b4',
    messagingSenderId: '736055369565',
    projectId: 'flutter-firebase-97df9',
    storageBucket: 'flutter-firebase-97df9.firebasestorage.app',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6tiYNJ1rIg6G4DPFHU6fH9RHCsKgJddE',
    appId: '1:736055369565:web:6a5a356f20caa83fa0d2b4',
    messagingSenderId: '736055369565',
    projectId: 'flutter-firebase-97df9',
    authDomain: 'flutter-firebase-97df9.firebaseapp.com',
    storageBucket: 'flutter-firebase-97df9.firebasestorage.app',
    measurementId: 'G-7ME48DV26H',
  );
}
